### ISSUE TITLE
Modif claim

### ISSUE THREAD

**Issue by DebHugo** [AyzrixYTB/SimpleFaction#15]
Ajoute dans la config une option:
power-pour-tous-les-claims: true
power : 100

Sa veut dire que si c'est ton premier claim ou ton 100e sa te couteras quand même 100 de powers car là tu es obligé de noté 100 fois. Si c'est sur false alors c'est encore le système actuel (ducoup le power sert à rien).

Rajoute aussi, si possible, un système qui fait que les claim doivent forcément être collé (configurable bien évidemment)
Voilà !

**Comment by AyzrixYTB** [comment]
Hello, I really don't see the point of this. Putting an infinity of claims is not a good idea for a server and therefore I think this system is the best idea for limiting that. On the other hand, for the idea of ​​collide claims, it's not a bad idea !

**Comment by DebHugo** [comment]
Ok as you want

**Comment by AyzrixYTB** [comment]
> Ok as you want

We have just remake the claim system.
