### ISSUE TITLE
GUI [Enhancement]

### ISSUE THREAD

**Issue by notacoderr** [AyzrixYTB/SimpleFaction#2]
Chest Inventory UI || Form UI support would be a cherry on top ;)

p.s: could be an extension plugin.

**Comment by AyzrixYTB** [comment]
Thank you for your idea, it will be added to the future additions list in the next commit 😉

**Comment by reda218** [comment]
Ajouté une sorte de générateur a power qui peux être endommagé par des faction enemy et récupérer tout sont contenue et qui peux être réparer pour le générateur je propose de le mettre à la place du crystal de l'ender

**Comment by Steelfri** [comment]
on est pas sur symphonia
