### ISSUE TITLE
Factions not saving after restart.

### ISSUE THREAD

**Issue by BrahmjotSingh0** [AyzrixYTB/SimpleFaction#27]
Hey hello! I am using your simple Faction plugin . For some reason it's not saving factions. I am using SQL lite for saving factions but whenni checked only the one Faction which I created is saved and others aren't and they got removed after restarting the server. Idk if it's a bug or something

**Comment by AyzrixYTB** [comment]
> Hey hello! I am using your simple Faction plugin . For some reason it's not saving factions. I am using SQL lite for saving factions but whenni checked only the one Faction which I created is saved and others aren't and they got removed after restarting the server. Idk if it's a bug or something

Hello, I am using SimpleFaction for my server and some other servers are using SimpleFaction. No one has this problem. Check that you are using the latest version available on poggit.
