### ISSUE TITLE
[Enhancement] Add a /f topftxt

### ISSUE THREAD

**Issue by UnEnanoMas** [AyzrixYTB/SimpleFaction#30]
![image](https://user-images.githubusercontent.com/63286108/115015576-2b23cb00-9eb4-11eb-9b99-87a0c79b7ec2.png)

I think it would be nice to add a floating text for the plugin.

It is not something that everyone is going to need, but it is something that is eye-catching and people like to see without using commands

In the floating text it says:

Top factions with more power
1.- (Name of the faction) with (power) of power and (number of players) players

**Comment by AyzrixYTB** [comment]
Good idea, next update ;)
