### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by UnEnanoMas** [AyzrixYTB/SimpleFaction#31]
```
[17.04 16:57:25 [Server] Server thread/CRITICAL TypeError: "Argument 2 passed to pocketmine\entity\Entity::createEntity() must be an instance of pocketmine\level\Level, null given, called in /plugins/SimpleFaction-master/src/Ayzrix/SimpleFaction/Main.php on line 118" (EXCEPTION) in "pmsrc/src/pocketmine/entity/Entity" at line 377
17.04 16:57:25 [Server] Server thread/CRITICAL #0 plugins/SimpleFaction-master/src/Ayzrix/SimpleFaction/Main(118): pocketmine\entity\Entity::createEntity(string[18] FloatingTextEntity, NULL , object pocketmine\nbt\tag\CompoundTag)
17.04 16:57:25 [Server] Server thread/CRITICAL #1 plugins/SimpleFaction-master/src/Ayzrix/SimpleFaction/Main(70): Ayzrix\SimpleFaction\Main->initFloatingText()
17.04 16:57:25 [Server] Server thread/CRITICAL #2 pmsrc/src/pocketmine/plugin/PluginBase(116): Ayzrix\SimpleFaction\Main->onEnable()
17.04 16:57:25 [Server] Server thread/CRITICAL #3 pmsrc/src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
17.04 16:57:25 [Server] Server thread/CRITICAL #4 pmsrc/src/pocketmine/Server(1785): pocketmine\plugin\PluginManager->enablePlugin(object Ayzrix\SimpleFaction\Main)
17.04 16:57:25 [Server] Server thread/CRITICAL #5 pmsrc/src/pocketmine/Server(1771): pocketmine\Server->enablePlugin(object Ayzrix\SimpleFaction\Main)
17.04 16:57:25 [Server] Server thread/CRITICAL #6 pmsrc/src/pocketmine/Server(1584): pocketmine\Server->enablePlugins(integer 1)
17.04 16:57:25 [Server] Server thread/CRITICAL #7 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
17.04 16:57:25 [Server] Server thread/CRITICAL #8 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
17.04 16:57:25 [Server] Server thread/CRITICAL #9 pmsrc(11): require(string[103] phar:///custom-php7.4.phar/src/po)
17.04 16:57:25 [Server] Server thread/INFO Disabling SimpleFaction v1.5.0
```

Lats vers of all

**Comment by AyzrixYTB** [comment]
> ```
> [17.04 16:57:25 [Server] Server thread/CRITICAL TypeError: "Argument 2 passed to pocketmine\entity\Entity::createEntity() must be an instance of pocketmine\level\Level, null given, called in /plugins/SimpleFaction-master/src/Ayzrix/SimpleFaction/Main.php on line 118" (EXCEPTION) in "pmsrc/src/pocketmine/entity/Entity" at line 377
> 17.04 16:57:25 [Server] Server thread/CRITICAL #0 plugins/SimpleFaction-master/src/Ayzrix/SimpleFaction/Main(118): pocketmine\entity\Entity::createEntity(string[18] FloatingTextEntity, NULL , object pocketmine\nbt\tag\CompoundTag)
> 17.04 16:57:25 [Server] Server thread/CRITICAL #1 plugins/SimpleFaction-master/src/Ayzrix/SimpleFaction/Main(70): Ayzrix\SimpleFaction\Main->initFloatingText()
> 17.04 16:57:25 [Server] Server thread/CRITICAL #2 pmsrc/src/pocketmine/plugin/PluginBase(116): Ayzrix\SimpleFaction\Main->onEnable()
> 17.04 16:57:25 [Server] Server thread/CRITICAL #3 pmsrc/src/pocketmine/plugin/PluginManager(552): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
> 17.04 16:57:25 [Server] Server thread/CRITICAL #4 pmsrc/src/pocketmine/Server(1785): pocketmine\plugin\PluginManager->enablePlugin(object Ayzrix\SimpleFaction\Main)
> 17.04 16:57:25 [Server] Server thread/CRITICAL #5 pmsrc/src/pocketmine/Server(1771): pocketmine\Server->enablePlugin(object Ayzrix\SimpleFaction\Main)
> 17.04 16:57:25 [Server] Server thread/CRITICAL #6 pmsrc/src/pocketmine/Server(1584): pocketmine\Server->enablePlugins(integer 1)
> 17.04 16:57:25 [Server] Server thread/CRITICAL #7 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[48] /, string[56] /plugins/)
> 17.04 16:57:25 [Server] Server thread/CRITICAL #8 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
> 17.04 16:57:25 [Server] Server thread/CRITICAL #9 pmsrc(11): require(string[103] phar:///custom-php7.4.phar/src/po)
> 17.04 16:57:25 [Server] Server thread/INFO Disabling SimpleFaction v1.5.0
> ```
> 
> 
> Lats vers of all

Update your config and put a valid level for the floatingtext

**Comment by UnEnanoMas** [comment]
I have deleted the configuration and I have reset the server, and I keep putting the same thing

Also I have not put the floating text anywhere :/

**Comment by AyzrixYTB** [comment]
> I have deleted the configuration and I have reset the server, and I keep putting the same thing
> 
> Also I have not put the floating text anywhere :/

so just put floating_text on false if you don’t want it

**Comment by UnEnanoMas** [comment]
Now it works, I changed the world, how weird it is xd

Ty
