### ISSUE TITLE
[FR] Support with ScorehudX

### ISSUE THREAD

**Issue by UnEnanoMas** [AyzrixYTB/SimpleFaction#32]
I think it would be great to add support for scorehudX to show kills, faction name, power etc.

**Comment by AyzrixYTB** [comment]
> I think it would be great to add support for scorehudX to show kills, faction name, power etc.

It's a good idea but I don't know if I would.

**Comment by UnEnanoMas** [comment]
Why?

**Comment by Willtom999** [comment]
I did the Simplefaction Scorehud if you want to tell me @UnEnanoMas

**Comment by AyzrixYTB** [comment]
> the Simplefaction Scorehud if you want to tell me @UnEnanoMas

U can just make a pull request if you want
