### ISSUE TITLE
Server Restart/Reload Kicked every Player out of their Faction

### ISSUE THREAD

**Issue by Yandura** [AyzrixYTB/SimpleFaction#33]
Plugin worked fine for about 2-3 weeks until i changed the power_gain_per_kill to 50 for a DOUBLE PVP REWARD WEEKEND.
When it changed it back to 25 power per kill and did a server restart, every player was removed from their faction.  

Only the 'faction' table in the SimpleFaction.db remained, but the 'players', 'home', and 'lang' tables were all deleted.
My players worked a long time for their power, only to have it reset and kick them out losing their home warps.  No errors or anything, just empty factions upon a server restart.

I don't know what it is, but there is something critically wrong with this plugin for it to reset the entire player factions database.  Very disappointing.

**Comment by AyzrixYTB** [comment]
> Plugin worked fine for about 2-3 weeks until i changed the power_gain_per_kill to 50 for a DOUBLE PVP REWARD WEEKEND.
> When it changed it back to 25 power per kill and did a server restart, every player was removed from their faction.
> 
> Only the 'faction' table in the SimpleFaction.db remained, but the 'players', 'home', and 'lang' tables were all deleted.
> My players worked a long time for their power, only to have it reset and kick them out losing their home warps. No errors or anything, just empty factions upon a server restart.
> 
> I don't know what it is, but there is something critically wrong with this plugin for it to reset the entire player factions database. Very disappointing.

Idk why, because I don't have any of this errors

**Comment by Yandura** [comment]
It seems to be a problem with the database getting messed up during resets.  I’m not the only one having this error, look in the comments on poggit.  It renders the plugin basically unusable

**Comment by AyzrixYTB** [comment]
> It seems to be a problem with the database getting messed up during resets. I’m not the only one having this error, look in the comments on poggit. It renders the plugin basically unusable

Try the new 1.6.0 version and tell me if that's work now X)
