### ISSUE TITLE
Plusieurs problèmes URGENT

### ISSUE THREAD

**Issue by cptneodyme** [AyzrixYTB/SimpleFaction#34]
- On peut se faire taper dans NOS propres claims.
- On peut ouvrir et accéder au contenue des fours dans les autres claims
- On peut ouvrir / fermer les portes et les trappes dans les autres claims
- Quand quelqu'un rejoind la faction, le power n'augmente pas

**Comment by AyzrixYTB** [comment]
``On peut se faire taper dans NOS propres claims.`` It's a Faction system, not a plot system ?
``Quand quelqu'un rejoind la faction, le power n'augmente pas`` That's a good idea for a future addition
