### ISSUE TITLE
[Question] ScoreHudX

### ISSUE THREAD

**Issue by MrBlasyMSK** [AyzrixYTB/SimpleFaction#40]
Is ScoreHUD V6 Addon compatible with the latest version of ScoreHUD?

If the answer is yes, I would like to know which {tags} are the ones to put

If the answer is no, could you make a version for it?

Thx

**Comment by AyzrixYTB** [comment]
> Is ScoreHUD V6 Addon compatible with the latest version of ScoreHUD?
> 
> If the answer is yes, I would like to know which {tags} are the ones to put
> 
> If the answer is no, could you make a version for it?
> 
> Thx

Yes it is and there is the tags

simplefaction.faction
simplefaction.power
simplefaction.money
simplefaction.rank
