### ISSUE TITLE
Player problem

### ISSUE THREAD

**Issue by Refaltor77** [AyzrixYTB/SimpleFaction#41]
Hi!
When I was reading your code, I noticed that you were using the nickname of the players, 
which can be a problem: if the player changes his nickname.

Proposed solution: Used the Xuid rather than the nicknames of the players :)

**Comment by AyzrixYTB** [comment]
> Hi!
> When I was reading your code, I noticed that you were using the nickname of the players,
> which can be a problem: if the player changes his nickname.
> 
> Proposed solution: Used the Xuid rather than the nicknames of the players :)

This is not really a problem and unfortunately I cannot change this anymore as it would ruin all the backups of those who are currently using it.
