### ISSUE TITLE
Problem with factions

### ISSUE THREAD

**Issue by MrBlasyMSK** [AyzrixYTB/SimpleFaction#42]
Many of my players can not delete, invite and do many things with the factions, and even I try to delete the factions with / f admin delete name does not let me do it, it says that they do not exist.

Please look at the plugin code because I already have several complaining

Even a player every time I restart the server his faction changes from "LakeCountry" to "Mar" out of nowhere, he always puts Mar

**Comment by AyzrixYTB** [comment]
> Many of my players can not delete, invite and do many things with the factions, and even I try to delete the factions with / f admin delete name does not let me do it, it says that they do not exist.
> 
> Please look at the plugin code because I already have several complaining
> 
> Even a player every time I restart the server his faction changes from "LakeCountry" to "Mar" out of nowhere, he always puts Mar

Please tell me more about that, are you using the last version, (1.6.5) ?

**Comment by MrBlasyMSK** [comment]
> > Many of my players can not delete, invite and do many things with the factions, and even I try to delete the factions with / f admin delete name does not let me do it, it says that they do not exist.
> > Please look at the plugin code because I already have several complaining
> > Even a player every time I restart the server his faction changes from "LakeCountry" to "Mar" out of nowhere, he always puts Mar
> 
> Please tell me more about that, are you using the last version, (1.6.5) ?

Yes, I am using dev75

**Comment by MrBlasyMSK** [comment]
https://streamable.com/hsjkhw 
@AyzrixYTB 

For example, it puts me that the faction does not exist, when it does exist, or many players try to invite someone and they do not let them

**Comment by AyzrixYTB** [comment]
> https://streamable.com/hsjkhw
> @AyzrixYTB
> 
> For example, it puts me that the faction does not exist, when it does exist, or many players try to invite someone and they do not let them

Can you please drop here your sqlite data file ?

**Comment by MrBlasyMSK** [comment]
[database.zip](https://github.com/AyzrixYTB/SimpleFaction/files/6895999/database.zip)

**Comment by MrBlasyMSK** [comment]
Do you know how long it will take to fix it? My players are a little bit desperate because their Factions are bugged after reboots (to some)

@AyzrixYTB

**Comment by AyzrixYTB** [comment]
Why do you give me the FactionsPro database ? That's not my plugin :')
