### ISSUE TITLE
Bug with player factions and invites

### ISSUE THREAD

**Issue by MrBlasyMSK** [AyzrixYTB/SimpleFaction#44]
[SimpleFactionDB.zip](https://github.com/AyzrixYTB/SimpleFaction/files/6919774/SimpleFactionDB.zip)
#42 Sorry I sent you the bad database, I got confused with the data plugin that I had not deleted from the old factions, sorry xd

**Comment by AyzrixYTB** [comment]
No problem, I check that

**Comment by AyzrixYTB** [comment]
I think that's bc your data file comes from an old version and I have fix all mysql/sqlite problem in the last version

**Comment by MrBlasyMSK** [comment]
So ... should I delete the database?

> I think that's bc your data file comes from an old version and I have fix all mysql/sqlite problem in the last version
