### ISSUE TITLE
Factions keep renaming to player names Dev 76

### ISSUE THREAD

**Issue by MrBlasyMSK** [AyzrixYTB/SimpleFaction#47]
For some strange reason, some players get the faction name renamed to their name and then not let them leave or do anything.
(Crash in version 76-> #46 )

I deleted the database of the factions and I am using the last one generated with dev 76, that is, it is a code error of the plugin not from an old database

Pls fix it 
[Database.zip](https://github.com/AyzrixYTB/SimpleFaction/files/6948981/Database.zip)

**Comment by jadperr** [comment]
> Untuk beberapa alasan aneh, beberapa pemain mendapatkan nama faksi yang diubah namanya menjadi nama mereka dan kemudian tidak membiarkan mereka pergi atau melakukan apa pun.
> (Macet di versi 76-> #46 )
> 
> Saya menghapus basis data faksi dan saya menggunakan yang terakhir dibuat dengan dev 76, yaitu, ini adalah kesalahan kode plugin bukan dari basis data lama
> 
> Tolong perbaiki
> [Database.zip](https://github.com/AyzrixYTB/SimpleFaction/files/6948981/Database.zip)

Same Issue

**Comment by AyzrixYTB** [comment]
Duplicate of #46
