### ISSUE TITLE
Bug de update

### ISSUE THREAD

**Issue by willtom6666** [AyzrixYTB/SimpleFaction#48]
Bonjour je voudrais vous dire que y’a un bug quand je crée ma faction sur purechat bah la faction s’affiche pas mais quand je déco reco bah il s’affiche 
![41CE7B97-1A46-4393-A100-0B0659145E68](https://user-images.githubusercontent.com/72766965/128653094-53a669ff-5bc2-4718-9c80-af5f82918ecd.png)
![0E2965C9-8AA6-41CD-9BE8-ACA050DE4D62](https://user-images.githubusercontent.com/72766965/128653107-d6114423-e13c-43c4-8bcb-2b58065a76e7.png)
![0F85C665-CEC1-42D6-9E8D-DFEBB95FC800](https://user-images.githubusercontent.com/72766965/128653109-4e6c5768-f990-47c6-b8ab-28d5c771f420.png)

**Comment by willtom6666** [comment]
Sais un bug sur la nametag

**Comment by AyzrixYTB** [comment]
That's Purechat and not SimpleFaction.
