### ISSUE TITLE
[Suggestion] Adding SafeZone

### ISSUE THREAD

**Issue by Adam1609** [AyzrixYTB/SimpleFaction#5]
It is hard for admin to create a faction that other players can't break but what about the SafeZone options? I know that it is not simple but just a suggestion.

**Comment by AyzrixYTB** [comment]
What do you mean by adding a safezone? The possibility of creating an infinite number of safezones? Or just define the server spawn ?

**Comment by Adam1609** [comment]
The possibility of creating an infinite number of safezone, yes.

**Comment by Steelfri** [comment]
emêcher de claim dans des endroits spéciaux aussi (genre spawn)
