### ISSUE TITLE
A very big problem that has not been fixed for 3 months.

### ISSUE THREAD

**Issue by zpwrd** [AyzrixYTB/SimpleFaction#54]
When you invite a player to a faction and he accepts the invitation, everything is fine. After restarting the server, all participants (except the leader) become phantom. Their clan tag becomes the player's nickname. They are phantom because if you hit them, the player (who tried to hit) kicks because of Internal Server error (undefined index: {player name}).
This is corrected by deleting the fractions database.

ErrorException: "Undefined index: Zipov" (EXCEPTION) in "plugins/SimpleFaction/src/Ayzrix/Simple
Faction/API/FactionsAPI" at line 653

**Comment by zpwrd** [comment]
Using last version/

**Comment by AyzrixYTB** [comment]
Try the new version X)
