### ISSUE TITLE
[Suggestion] Send information when entering a claimed faction

### ISSUE THREAD

**Issue by Adam1609** [AyzrixYTB/SimpleFaction#8]
It is hard to keep up with /f border and /f map because we have to input command a lot. With this suggestion, new player and old player should aware of the faction they entered or even their own faction claimed land.

**Comment by AyzrixYTB** [comment]
> It is hard to keep up with /f border and /f map because we have to input command a lot. With this suggestion, new player and old player should aware of the faction they entered or even their own faction claimed land.

No, you can just do /f border and /f map on :). But that’s a good idea

**Comment by AyzrixYTB** [comment]
Can you describe in more detail?

Do you just want:

(prefix) Now leaving (zone)
(prefix) Now enterring (zone)

Zones: Safezone (future), Faction Name (claim) or Wlderness 

?
